apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: image-reference
      type: string
  workspaces:
    - name: pipeline-workspace
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: pipeline-workspace
    - name: npminstall
      runAfter: [clone]
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: tests
      runAfter: [npminstall]
      taskRef:
        name: jasmine
      workspaces:
        - name: source
          workspace: pipeline-workspace
    - name: build
      runAfter: [tests]
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.image-reference)
      workspaces:
        - name: source
          workspace: pipeline-workspace
